#!/bin/bash
# Regenerates docs/gfx906-patches.md: every commit on the gfx906 branch that is not in upstream llama.cpp, in two groups
# (the Exabit series on top of the fork state, and the mx-llama.cpp fork state itself). Run after every merge of upstream master:
#   scripts/gfx906/patch-inventory.sh > docs/gfx906-patches.md
set -e
cd "$(dirname "$0")/../.."
BR=${BR:-gfx906}; UP=${UP:-master}; FORK=${FORK:-mxxm-b10912}
BASE=$(git merge-base $FORK $UP)
UPHEAD=$(git rev-parse --short $UP); MERGE=$(git log --merges --format=%h -1 $BR)
FMT='%h  %as  %an  %s'
echo "# Every commit on \`$BR\` that is not in upstream llama.cpp"
echo
echo "Generated by \`scripts/gfx906/patch-inventory.sh\` on $(date -u +%Y-%m-%d); regenerate after every merge. Upstream mirror branch \`$UP\` at $UPHEAD;"
echo "fork state \`$FORK\` (mx-llama.cpp, ML-gfx906) whose upstream base is $(git rev-parse --short $BASE); the branch's merge commit is $MERGE."
echo "Runtime knobs and measured effects: \`GFX906.md\`; build recipe \`scripts/gfx906/build.sh\`; environment \`scripts/gfx906/env.sh\`."
echo
echo "## Exabit series ($(git rev-list --no-merges --count $BR ^$UP ^$FORK) commits on top of the fork state; measured on the four-die box, oldest first)"
echo
echo '```'
git log --no-merges --reverse --format="$FMT" $BR ^$UP ^$FORK
echo '```'
echo
echo "## mx-llama.cpp fork state (tag b10912: $(git rev-list --no-merges --count $FORK ^$BASE) commits over upstream $(git rev-parse --short $BASE), oldest first; features in FEATURES.md)"
echo
echo '```'
git log --no-merges --reverse --format="$FMT" $FORK ^$BASE
echo '```'
echo
echo "## Files the branch changes against upstream \`$UP\` (excluding docs and scripts/gfx906)"
echo
echo '```'
git diff --stat=120 $UP $BR -- . ':!docs' ':!scripts/gfx906' ':!GFX906.md' ':!FEATURES.md' | tail -1
git diff --name-only $UP $BR -- . ':!docs' ':!scripts/gfx906' ':!GFX906.md' ':!FEATURES.md' | sed 's/^/  /'
echo '```'
